### ISSUE TITLE
thank for your lib,ask for a help!

### ISSUE THREAD

**Issue by powerfulyang** [tarikhagustia/laravel-mt5#1]
I'm not a phper. how can i run your lib for a test?
just like 
```
php index.php
```
in terminal

**Comment by tarikhagustia** [comment]
This package is not yet available for testing, to use this package you must install laravel 6.

**Comment by powerfulyang** [comment]
thank your reply~
**not use php.**
actually, I post the bytes[] buffer to my mt5server url (https://mt5.zhaodaishu.com) in nodejs
```
00A600010AUTH_START|VERSION=2190|AGENT=WebAPI|LOGIN=1000|TYPE=MANAGER|CRYPT_METHOD=NONE|\r\n
```
+ 00A600010 (utf8)
+ AUTH_START|VERSION=2190|AGENT=WebAPI|LOGIN=1000|TYPE=MANAGER|CRYPT_METHOD=NONE|\r\n(utf16le)
--- 
a simple test for auth_start
but got a httpcode 400 Bad Request.
do i have some error in my realize?
can you help me to figure out ?
```
mt5server 
https://mt5.zhaodaishu.com 
login=1000
password=123.com
``` 
thanks,

**Comment by powerfulyang** [comment]
does webapi is a http post request？
can you create a account name='你好' in my server？password and server show on above

**Comment by tarikhagustia** [comment]
try to using port 443 and you need to allow your MT5 server to allow web API

**Comment by powerfulyang** [comment]
yeah I'm using 443 port and allow web api,but i meet some questions!
via https i create an account througn the url
```
/user_add?login={account number}&pass_main={main password}&pass_investor={investor password}
&rights={user rights}&group={group name}&name={client name}&company={company}
&language={language}&country={country}&city={city}&state={region}&zipcode={postal code}
&address={address}&phone={phone number}&email={email}&id={document id}&status={status}
&comment={comment}&color={color}&pass_phone={phone password}&leverage={leverage}
&account={external bank account number}&agent={agent account}
{JSON description of the client record}
```
i have created an account. but i cann't realize the command formatter
```
USER_ADD|LOGIN=xxxx|PASS_MAIN=xxxx|PASS_INVESTOR=xxxx|
RIGHTS=|GROUP=xxxx|NAME=xxxx|COMPANY=|LANGUAGE=|
CITY=|STATE=|ZIPCODE=|ADDRESS=|PHONE=|EMAIL=|ID=|STATUS=|COMMENT=|
COLOR=|PASS_PHONE=|LEVERAGE=|AGENT=|\r\n
Description of a client in the JSON format
```
does it also a http request?

**Comment by tarikhagustia** [comment]
did you get response from https api ?, send me direct emai if u have any question, i will close this issue

thanks

**Comment by jayeshtechextensor** [comment]
Hello,
I am trying to set this library in my localhost but didn't get a response. can you please help me?
