### ISSUE TITLE
Not enough permission in create trade user account

### ISSUE THREAD

**Issue by vnxz** [tarikhagustia/laravel-mt5#3]
I follow your steps , but Not enough permission in create user,
why happen ?

need to register mt5 account by myself first and need to use this credientials in env?
why?
```
 public function store(Request $request)
    {
        $api = new LaravelMt5();
$user = new User();
$user->setName("John Due");
$user->setEmail("john@due.com");
$user->setGroup("demo\demoforex");
$user->setLeverage("50");
$user->setPhone("0856123456");
$user->setAddress("Sukabumi");
$user->setCity("Sukabumi");
$user->setState("Jawa Barat");
$user->setCountry("Indonesia");
$user->setZipCode(1470);
$user->setMainPassword("Secure123");
$user->setInvestorPassword("NotSecure123");
$user->setPhonePassword("NotSecure123");

$result = $api->createUser($user);


 dd($result);

```
can you please help me.

**Comment by tarikhagustia** [comment]
looks like your manager account don't have access to create account

**Comment by vnxz** [comment]
> looks like your manager account don't have access to create account

where can I get manager account bro

**Comment by tarikhagustia** [comment]
> > looks like your manager account don't have access to create account
> 
> where can I get manager account bro

the LOGIN used when using this packge

**Comment by vnxz** [comment]
> > > looks like your manager account don't have access to create account
> > 
> > 
> > where can I get manager account bro
> 
> the LOGIN used when using this packge

package is open source, So where is Login

**Comment by vnxz** [comment]
> > > looks like your manager account don't have access to create account
> > 
> > 
> > where can I get manager account bro
> 
> the LOGIN used when using this packge

how can I get manager account bro.

**Comment by netbee1136** [comment]
/********************************************/


use JulioOrtaHdz\PhpMeta\MetaTraderClient;
use JulioOrtaHdz\PhpMeta\Entities\User as MetaFiveUser;
use JulioOrtaHdz\PhpMeta\src\Lib\MTEnDealAction;

  /********************************************/
$user = new MetaFiveUser();
$user->setName("John Due Test");
$user->setEmail("john@due.com");
$user->setGroup("grouphere");
$user->setLeverage("50");
$user->setPhone("0856123456");
$user->setAddress("Sukabumi");
$user->setCity("Sukabumi");
$user->setState("Jawa Barat");
$user->setCountry("Indonesia");
$user->setZipCode(1470);
$user->setMainPassword("Secure123");
$user->setInvestorPassword("NotSecure123");
$user->setPhonePassword("NotSecure123");
$api = new MetaTraderClient($server, $port, $login, $password);
$result = $api->createUser($user);

JulioOrtaHdz \ PhpMeta \ Exceptions \ ConnectionException
PHP 8.1.18
9.52.8
**Invalid account**
getting this error on try to add new account , i am using the 

$server = "185.96.***.**";
$port = "443";
**$login = "200";** // provided by the client 
$password = "******l";

**Comment by tarikhagustia** [comment]
> /********************************************/
> 
> use JulioOrtaHdz\PhpMeta\MetaTraderClient; use JulioOrtaHdz\PhpMeta\Entities\User as MetaFiveUser; use JulioOrtaHdz\PhpMeta\src\Lib\MTEnDealAction;
> 
> /********************************************/ $user = new MetaFiveUser(); $user->setName("John Due Test"); $user->setEmail("[john@due.com](mailto:john@due.com)"); $user->setGroup("grouphere"); $user->setLeverage("50"); $user->setPhone("0856123456"); $user->setAddress("Sukabumi"); $user->setCity("Sukabumi"); $user->setState("Jawa Barat"); $user->setCountry("Indonesia"); $user->setZipCode(1470); $user->setMainPassword("Secure123"); $user->setInvestorPassword("NotSecure123"); $user->setPhonePassword("NotSecure123"); $api = new MetaTraderClient($server, $port, $login, $password); $result = $api->createUser($user);
> 
> JulioOrtaHdz \ PhpMeta \ Exceptions \ ConnectionException PHP 8.1.18 9.52.8 **Invalid account** getting this error on try to add new account , i am using the
> 
> $server = "185.96.***.**"; $port = "443"; **$login = "200";** // provided by the client $password = "******l";

probably you input the wrong manager web API password

**Comment by netbee1136** [comment]
I setup but now its give me this error **Invalid terminal type**

**Comment by tarikhagustia** [comment]
> I setup but now its give me this error **Invalid terminal type**

its because you put client credentials, this is require Manager credential
