### ISSUE TITLE
from where I get the values for the .env constants?

### ISSUE THREAD

**Issue by soyluismunoz** [tarikhagustia/laravel-mt5#5]
Where do I get these credentials from?

MT5_SERVER_IP=
MT5_SERVER_PORT=
MT5_SERVER_WEB_LOGIN=
MT5_SERVER_WEB_PASSWORD=

**Comment by meeprakash25** [comment]
same question

**Comment by tarikhagustia** [comment]
It's from metatrader server provider (maybe its your client, your company or broker)
